ferg:
  baudrate: 115200
  port_names: [Micro]
  serial_read_options: [quiet]
para:
  baudrate: 9600
  port_names: [SERIAL, Serial]
  serial_read_options: [logging, heatmass_PID]
waterscope:
  baudrate: 9600
  port_names: [ws]
  serial_read_options: [quiet]
